// Category Icons Mapping
// این فایل شامل آیکن‌های مناسب برای هر دسته‌بندی است

export const categoryIcons: { [key: string]: string } = {
  // سلامت (Healthcare)
  'hospital': '🏥',
  'medical-clinic': '🏥',
  'infirmary': '🏥',
  'medical-office': '👨‍⚕️',
  'counseling-centers': '💬',
  'medical-laboratory': '🔬',
  'pharmacy': '💊',
  'veterinarian': '🐾',
  
  // اقامت (Accommodation)
  'hotel': '🏨',
  'motel': '🏨',
  'guest-house': '🏠',
  'vernacular-accommodation': '🏡',
  
  // خرید (Shopping)
  'supermarket': '🛒',
  'shopping-mall': '🏬',
  'medicinal-herbs-store': '🌿',
  'clothing-store': '👕',
  'bag-and-shoes-shop': '👠',
  'cosmetics-store': '💄',
  'gold-store': '💍',
  'home-goods-and-accessories-store': '🛋️',
  'electrical-appliances-store': '📺',
  'rug-store': '🪑',
  'electrical-equipment-store': '⚡',
  'computer-store': '💻',
  'cell-phone-store': '📱',
  'camera-accessories-store': '📷',
  'audio-visual-equipment-shop': '📻',
  'florist': '🌸',
  'stationery-store': '📝',
  
  // دفاتر خدماتی (Government)
  'city-electronic-services-offices': '🏛️',
  'pishkhan-office': '🏛️',
  'police-10': '🚔',
  'social-security-office': '📋',
  'notary-public': '📜',
  'dispute-resolution-council': '⚖️',
  'judicial-services-bureau': '⚖️',
  'translation-office': '🌐',
  'post-office': '📮',
  'lawyer': '⚖️',
  
  // خوراکی (Food)
  'restaurant': '🍽️',
  'catering': '🍱',
  'tabakhi': '🍲',
  'dizi': '🍲',
  'jegaraki': '🍖',
  'ash-and-halim': '🥣',
  'fast-food-restaurant': '🍔',
  'coffee-shop': '☕',
  'ice-cream-and-juice-shop': '🍦',
  'confectionery': '🍰',
  'nuts-store': '🥜',
  'fruits-and-vegetables-sales': '🍎',
  'meat-and-protein-shop': '🥩',
  'iranian-bakery': '🥖',
  'dairy-shop': '🥛',
  
  // خدمات (Services)
  'parking': '🅿️',
  'atm': '🏧',
  'public-bathroom': '🚻',
  'mosque': '🕌',
  'shipping-company': '📦',
  'video-and-photo-studio': '📸',
  'travel-agency': '✈️',
  'makeup-and-trimming': '💇',
  'key-duplication-service': '🔑',
  'tailoring-clothes-showroom': '✂️',
  'dry-cleaner': '🧺',
  'estate-agency': '🏘️',
  'building-services': '🔨',
  'equipment-repair': '🔧',
  'bag-and-shoes-repair': '👞',
  
  // خدمات خودرو (Automotive)
  'auto-parts-store': '🔩',
  'car-servicing': '🔧',
  'car-inspection': '🚗',
  'plate-number-registration-center': '🚙',
  'car-evaluation-center': '📊',
  'car-wash': '🚿',
  'fuel-station': '⛽',
  
  // تفریح و ورزش (Sports & Entertainment)
  'pool': '🏊',
  'sports-club': '💪',
  'historical-place': '🏛️',
  'park': '🌳',
  'museum': '🏛️',
  'water-park': '🌊',
  'zoo': '🦁',
  'amusement-park': '🎢',
  'cinema': '🎬',
  'theater': '🎭',
  'art-gallery': '🖼️',
};

// تابع برای دریافت آیکن بر اساس slug
export function getCategoryIcon(slug: string): string {
  return categoryIcons[slug] || '📍'; // پیش‌فرض: آیکن موقعیت
}

// تابع برای دریافت آیکن بر اساس نام دسته (برای سازگاری با داده‌های قدیمی)
export function getCategoryIconByName(categoryName: string): string {
  const nameToSlug: { [key: string]: string } = {
    'بیمارستان': 'hospital',
    'کلینیک درمانی': 'medical-clinic',
    'درمانگاه': 'infirmary',
    'مطب پزشک': 'medical-office',
    'مرکز مشاوره': 'counseling-centers',
    'آزمایشگاه پزشکی': 'medical-laboratory',
    'داروخانه': 'pharmacy',
    'دامپزشکی': 'veterinarian',
    'هتل': 'hotel',
    'متل': 'motel',
    'مهمان‌سرا': 'guest-house',
    'اقامتگاه بوم‌گردی': 'vernacular-accommodation',
    'سوپرمارکت': 'supermarket',
    'مرکز خرید': 'shopping-mall',
    'عطاری': 'medicinal-herbs-store',
    'فروشگاه لباس': 'clothing-store',
    'فروشگاه کیف و کفش': 'bag-and-shoes-shop',
    'فروشگاه لوازم آرایشی بهداشتی': 'cosmetics-store',
    'طلا فروشی': 'gold-store',
    'تزیینات و دکوراسیون خانه': 'home-goods-and-accessories-store',
    'فروشگاه لوازم خانه': 'electrical-appliances-store',
    'فرش فروشی': 'rug-store',
    'الکتریکی': 'electrical-equipment-store',
    'فروشگاه کامپیوتری': 'computer-store',
    'فروشگاه تلفن همراه': 'cell-phone-store',
    'فروشگاه لوازم عکاسی و فیلمبرداری': 'camera-accessories-store',
    'فروشگاه صوتی و تصویری': 'audio-visual-equipment-shop',
    'گل فروشی': 'florist',
    'فروشگاه لوازم تحریر': 'stationery-store',
    'دفتر خدمات الکترونیک شهر': 'city-electronic-services-offices',
    'دفتر پیشخوان دولت': 'pishkhan-office',
    'پلیس + ۱۰': 'police-10',
    'دفتر بیمه تامین اجتماعی': 'social-security-office',
    'دفتر اسناد رسمی': 'notary-public',
    'شورای حل اختلاف': 'dispute-resolution-council',
    'دفتر خدمات قضایی': 'judicial-services-bureau',
    'دارالترجمه': 'translation-office',
    'دفتر پست': 'post-office',
    'دفتر وکالت': 'lawyer',
    'رستوران': 'restaurant',
    'تهیه غذا': 'catering',
    'طباخی': 'tabakhi',
    'دیزی‌سرا': 'dizi',
    'جگرکی': 'jegaraki',
    'آش و حلیم فروشی': 'ash-and-halim',
    'فست‌فود': 'fast-food-restaurant',
    'کافه': 'coffee-shop',
    'بستنی و آبمیوه فروشی': 'ice-cream-and-juice-shop',
    'شیرینی فروشی': 'confectionery',
    'آجیل و خشکبار فروشی': 'nuts-store',
    'میوه فروشی': 'fruits-and-vegetables-sales',
    'فروشگاه فرآورده‌های گوشتی': 'meat-and-protein-shop',
    'نانوایی': 'iranian-bakery',
    'لبنیاتی': 'dairy-shop',
    'پارکینگ': 'parking',
    'خودپرداز': 'atm',
    'سرویس بهداشتی': 'public-bathroom',
    'مسجد': 'mosque',
    'خدمات باربری': 'shipping-company',
    'آتلیه فیلم و عکس': 'video-and-photo-studio',
    'آژانس مسافرتی': 'travel-agency',
    'آرایش و پیرایش': 'makeup-and-trimming',
    'کلید سازی': 'key-duplication-service',
    'خیاطی': 'tailoring-clothes-showroom',
    'خشکشویی': 'dry-cleaner',
    'مشاور املاک': 'estate-agency',
    'خدمات ساختمانی': 'building-services',
    'مرکز تعمیر تجهیزات برقی': 'equipment-repair',
    'مرکز تعمیر کیف و کفش': 'bag-and-shoes-repair',
    'فروشگاه قطعات یدکی خودرو': 'auto-parts-store',
    'تعمیرگاه خودرو': 'car-servicing',
    'مرکز معاینه فنی خودرو': 'car-inspection',
    'مرکز تعویض پلاک': 'plate-number-registration-center',
    'مرکز کارشناسی خودرو': 'car-evaluation-center',
    'کارواش': 'car-wash',
    'جایگاه سوخت': 'fuel-station',
    'استخر': 'pool',
    'باشگاه ورزشی': 'sports-club',
    'مکان تاریخی': 'historical-place',
    'پارک': 'park',
    'موزه': 'museum',
    'پارک آبی': 'water-park',
    'باغ وحش': 'zoo',
    'شهربازی': 'amusement-park',
    'سینما': 'cinema',
    'تئاتر و تماشاخانه': 'theater',
    'گالری': 'art-gallery',
  };
  
  const slug = nameToSlug[categoryName];
  return slug ? getCategoryIcon(slug) : '📍';
}

